"""empty message

Revision ID: 135bd9f2b228
Revises: 8b90963ab45e
Create Date: 2020-06-26 22:33:25.191797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135bd9f2b228'
down_revision = '8b90963ab45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('abbreviation', sa.String(), nullable=True))
    op.drop_column('businesses', 'abreviation')
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('businesses', sa.Column('abreviation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'abbreviation')
    # ### end Alembic commands ###
