"""empty message

Revision ID: 41f3ca9ef19e
Revises: 5ab60b98bac7
Create Date: 2020-06-19 14:06:15.842313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f3ca9ef19e'
down_revision = '5ab60b98bac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'businesses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'user_id')
    # ### end Alembic commands ###
