"""empty message

Revision ID: 58c3728ffa7a
Revises: 135bd9f2b228
Create Date: 2020-06-29 00:53:25.449017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c3728ffa7a'
down_revision = '135bd9f2b228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_details', sa.Column('transaction_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_details', 'transaction_date')
    # ### end Alembic commands ###
