"""empty message

Revision ID: 632380672d70
Revises: e34062f07da7
Create Date: 2020-06-30 16:00:21.947040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632380672d70'
down_revision = 'e34062f07da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_file_name_key', 'transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('transactions_file_name_key', 'transactions', ['file_name'])
    # ### end Alembic commands ###
