"""empty message

Revision ID: 6ea4f17a8298
Revises: 57ed02952766
Create Date: 2020-07-17 22:54:37.370607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea4f17a8298'
down_revision = '57ed02952766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('entity', sa.String(), nullable=True))
    op.drop_column('businesses', 'Entity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('Entity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'entity')
    # ### end Alembic commands ###
