"""empty message

Revision ID: 744849d8713f
Revises: 41f3ca9ef19e
Create Date: 2020-06-19 15:35:18.152534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744849d8713f'
down_revision = '41f3ca9ef19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('countries', sa.JSON(), nullable=True))
    op.add_column('businesses', sa.Column('country', sa.String(), nullable=True))
    op.drop_column('businesses', 'Countries_of_operation')
    op.drop_column('businesses', 'Country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('Country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('Countries_of_operation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'country')
    op.drop_column('businesses', 'countries')
    # ### end Alembic commands ###
