"""empty message

Revision ID: 80daf5ed5eb9
Revises: 81ef3bfe4246
Create Date: 2020-07-01 00:10:43.589670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80daf5ed5eb9'
down_revision = '81ef3bfe4246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_date')
    op.drop_column('transactions', 'due_date')
    # ### end Alembic commands ###
