"""empty message

Revision ID: 81ef3bfe4246
Revises: 632380672d70
Create Date: 2020-07-01 00:09:14.192216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ef3bfe4246'
down_revision = '632380672d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'due_date')
    op.drop_column('transactions', 'transaction_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('due_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
