"""empty message

Revision ID: e34062f07da7
Revises: 63336b38956e
Create Date: 2020-06-30 15:54:50.966282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34062f07da7'
down_revision = '63336b38956e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('file_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['file_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'file_name')
    # ### end Alembic commands ###
