"""empty message

Revision ID: facca51ef3c1
Revises: 58c3728ffa7a
Create Date: 2020-06-29 01:11:43.039485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facca51ef3c1'
down_revision = '58c3728ffa7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_details', sa.Column('name', sa.SmallInteger(), nullable=False))
    op.drop_column('transaction_details', 'transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_details', sa.Column('transaction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction_details', 'name')
    # ### end Alembic commands ###
